/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;



import java.io.FileReader;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

class Configuration {
    private static boolean mousePressed = false;

    private Map<String, String> keyValues;

    public Configuration() {
        keyValues = new LinkedHashMap<>();
    }

    public void setKeyValue(String key, String value) {
        keyValues.put(key, value);
    }

    //to take key and return value 
    public String getKeyValue(String key) {
        return keyValues.get(key);
    }

    public static void setMousePressed(boolean status) {
        mousePressed = status;
    }

    public void writeToFile(String fileName) {
    try (FileWriter fileWriter = new FileWriter(fileName)) {
        for (Map.Entry<String, String> entry : keyValues.entrySet()) {
            // Write each key-value pair in the format "KEY: VALUE"
            fileWriter.write(entry.getKey() + ": " + entry.getValue() + "\n");
        }
    } catch (IOException e) {
        System.out.println("An error occurred while writing to file: " + e.getMessage());
    }
}


    public void loadFromFile(String fileName) {
        try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = reader.readLine()) != null) {
                //"KEY: VALUE"
                String[] parts = line.split(":");
                if (parts.length == 2) {
                    String key = parts[0].trim();
                    String value = parts[1].trim();
                    setKeyValue(key, value);/************start storing**************/
                }
            }
        } catch (IOException e) {
            System.out.println("An error occurred while reading from file: " + e.getMessage());
        }
    }
    
    
     public void UpdateComboBox(javax.swing.JComboBox<String>[] comboBoxes) {
        int i = 0;
        for (Map.Entry<String, String> entry : keyValues.entrySet()) {
            comboBoxes[i].setSelectedItem(entry.getValue());
             System.out.println(entry.getValue());
            i++;
        }
    }

    
    
    
    
    
}


/**
 *
 * @author minam
 */
public class firm1 extends javax.swing.JFrame {

    /**
     * Creates new form firm1
     */
    
    private Configuration config;
    
    private javax.swing.JComboBox<String>[] comboBoxes;

    public firm1() {
        
        config = new Configuration();
        config.loadFromFile("C:\\Users\\minam\\OneDrive\\Documents\\NetBeansProjects\\JavaApp\\src\\javaapp\\remoteConfig.txt");  //load key from file
        
        initComponents();
        
        
         comboBoxes = new javax.swing.JComboBox[] {
            ComboBoxKeyRight,
            ComboBoxKeyLeft,
            ComboBoxKeyUp,
            ComboBoxKeyDown,
            ComboBoxKeyAsterisk, 
            ComboBoxKeyHash, 
            ComboBoxKeyOk, 
            ComboBoxKey0,
            ComboBoxKey1,  
            ComboBoxKey2,
            ComboBoxKey3, 
            ComboBoxKey4, 
            ComboBoxKey5, 
            ComboBoxKey6,
            ComboBoxKey7, 
            ComboBoxKey8, 
            ComboBoxKey9
          
            
           
        };
         
         
        config.UpdateComboBox(comboBoxes);
        
        
    }
    
    public void UpdateComboBoxValue() {
        
        
        
        
        
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ComboBoxKey1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxKey2 = new javax.swing.JComboBox<>();
        ComboBoxKey3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ComboBoxKey4 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxKey5 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxKey6 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ComboBoxKey7 = new javax.swing.JComboBox<>();
        ComboBoxKey8 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ComboBoxKey0 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        ComboBoxKey9 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        ComboBoxKeyAsterisk = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        ComboBoxKeyHash = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        ComboBoxKeyOk = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        ComboBoxKeyUp = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        ComboBoxKeyDown = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        ComboBoxKeyRight = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        ComboBoxKeyLeft = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Key 1");

        ComboBoxKey1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKey1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Key 2");

        ComboBoxKey2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKey2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKey2ActionPerformed(evt);
            }
        });

        ComboBoxKey3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKey3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKey3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Key 3");

        ComboBoxKey4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKey4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKey4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Key 4");

        ComboBoxKey5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKey5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKey5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Key 8");

        jLabel7.setText("Key 5");

        ComboBoxKey6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKey6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKey6ActionPerformed(evt);
            }
        });

        jLabel8.setText("Key 6");

        ComboBoxKey7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKey7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKey7ActionPerformed(evt);
            }
        });

        ComboBoxKey8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKey8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKey8ActionPerformed(evt);
            }
        });

        jLabel9.setText("Key 7");

        jLabel10.setText("Key 0");

        ComboBoxKey0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKey0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKey0ActionPerformed(evt);
            }
        });

        jLabel11.setText("Key 9");

        ComboBoxKey9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKey9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKey9ActionPerformed(evt);
            }
        });

        jLabel12.setText("Key *");

        ComboBoxKeyAsterisk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKeyAsterisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKeyAsteriskActionPerformed(evt);
            }
        });

        jLabel13.setText("Key #");

        ComboBoxKeyHash.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKeyHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKeyHashActionPerformed(evt);
            }
        });

        jLabel14.setText("Key OK");

        ComboBoxKeyOk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKeyOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKeyOkActionPerformed(evt);
            }
        });

        jLabel15.setText("Key Up");

        ComboBoxKeyUp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKeyUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKeyUpActionPerformed(evt);
            }
        });

        jLabel16.setText("Key Down");

        ComboBoxKeyDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKeyDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKeyDownActionPerformed(evt);
            }
        });

        jLabel17.setText("Key Right");

        ComboBoxKeyRight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKeyRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKeyRightActionPerformed(evt);
            }
        });

        jLabel18.setText("Key Left");

        ComboBoxKeyLeft.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOUSE_RIGHT", "MOUSE_LEFT", "MOUSE_UP", "MOUSE_DOWN", "ARROW_RIGHT", "ARROW_LEFT", "LEFT_CLICK", "ARROW_DOWN", "TOGGLE_PRESENTATION", "CLOSE", "SCROLL_UP", "TOGGLE_HOLD", "SCROLL_DOWN", "PRTSC", "ARROW_UP", "PRESS_0", "PRESS_1", "PRESS_2", "PRESS_3", "PRESS_4", "PRESS_5", "PRESS_6", "PRESS_7", "PRESS_8", "PRESS_9", "F_11" }));
        ComboBoxKeyLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKeyLeftActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(204, 102, 255));
        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxKey9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(ComboBoxKey5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(ComboBoxKey8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ComboBoxKey7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ComboBoxKey6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(ComboBoxKey4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(ComboBoxKey3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ComboBoxKey2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ComboBoxKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBoxKey0, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ComboBoxKeyOk, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ComboBoxKeyHash, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ComboBoxKeyAsterisk, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ComboBoxKeyUp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addGap(18, 18, 18)
                                            .addComponent(ComboBoxKeyDown, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel18))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ComboBoxKeyLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ComboBoxKeyRight, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ComboBoxKey0, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(ComboBoxKeyAsterisk, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ComboBoxKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(ComboBoxKeyHash, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(ComboBoxKey2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(ComboBoxKey3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(ComboBoxKeyOk, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(ComboBoxKeyUp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(ComboBoxKey4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(ComboBoxKey6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(ComboBoxKeyDown, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(ComboBoxKeyRight, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ComboBoxKey7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(ComboBoxKeyLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ComboBoxKey8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ComboBoxKey5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ComboBoxKey9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKey1ActionPerformed
         /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_1", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKey1ActionPerformed

    private void ComboBoxKey2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKey2ActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_2", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKey2ActionPerformed

    private void ComboBoxKey3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKey3ActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_3", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKey3ActionPerformed

    private void ComboBoxKey4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKey4ActionPerformed
       /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_4", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKey4ActionPerformed

    private void ComboBoxKey5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKey5ActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_5", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKey5ActionPerformed

    private void ComboBoxKey6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKey6ActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_6", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKey6ActionPerformed

    private void ComboBoxKey7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKey7ActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_7", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKey7ActionPerformed

    private void ComboBoxKey8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKey8ActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_8", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKey8ActionPerformed

    private void ComboBoxKey0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKey0ActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_0", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKey0ActionPerformed

    private void ComboBoxKey9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKey9ActionPerformed
       /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_9", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKey9ActionPerformed

    private void ComboBoxKeyAsteriskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKeyAsteriskActionPerformed
       /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_PREVIOUS", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKeyAsteriskActionPerformed

    private void ComboBoxKeyHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKeyHashActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_NEXT", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKeyHashActionPerformed

    private void ComboBoxKeyOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKeyOkActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_ENTER", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKeyOkActionPerformed

    private void ComboBoxKeyUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKeyUpActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_UP", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKeyUpActionPerformed

    private void ComboBoxKeyDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKeyDownActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_DOWN", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKeyDownActionPerformed

    private void ComboBoxKeyRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKeyRightActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_RIGHT", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKeyRightActionPerformed

    private void ComboBoxKeyLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKeyLeftActionPerformed
        /* Get the selected item as a string */
        String selectedItem = ((javax.swing.JComboBox<String>) evt.getSource()).getSelectedItem().toString();
        /* set new Value */
        config.setKeyValue("KEY_LEFT", selectedItem);
        /* Now you can use selectedItem in your code */
        System.out.println("Selected item: " + selectedItem);
    }//GEN-LAST:event_ComboBoxKeyLeftActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        config.writeToFile("C:\\Users\\minam\\OneDrive\\Documents\\NetBeansProjects\\JavaApp\\src\\javaapp\\remoteConfig.txt");  //load key from file
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firm1().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxKey0;
    private javax.swing.JComboBox<String> ComboBoxKey1;
    private javax.swing.JComboBox<String> ComboBoxKey2;
    private javax.swing.JComboBox<String> ComboBoxKey3;
    private javax.swing.JComboBox<String> ComboBoxKey4;
    private javax.swing.JComboBox<String> ComboBoxKey5;
    private javax.swing.JComboBox<String> ComboBoxKey6;
    private javax.swing.JComboBox<String> ComboBoxKey7;
    private javax.swing.JComboBox<String> ComboBoxKey8;
    private javax.swing.JComboBox<String> ComboBoxKey9;
    private javax.swing.JComboBox<String> ComboBoxKeyAsterisk;
    private javax.swing.JComboBox<String> ComboBoxKeyDown;
    private javax.swing.JComboBox<String> ComboBoxKeyHash;
    private javax.swing.JComboBox<String> ComboBoxKeyLeft;
    private javax.swing.JComboBox<String> ComboBoxKeyOk;
    private javax.swing.JComboBox<String> ComboBoxKeyRight;
    private javax.swing.JComboBox<String> ComboBoxKeyUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
